controller:
  # 전용 컨트롤러가 사용할 고유 ingressClass (공용 nginx와 분리)
  ingressClass: keycloak
  ingressClassResource:
    name: keycloak
    controllerValue: "k8s.io/ingress-nginx-keycloak"
    default: false

  # 소스 IP 보존
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations: {}

  config:
    # 기본 원 IP 처리
    use-forwarded-headers: "true"
    enable-real-ip: "true"
    compute-full-forwarded-for: "true"

    # Cloudflare가 넣어주는 헤더를 '실제 클라이언트 IP'로 사용
    real-ip-header: "CF-Connecting-IP"

    # Cloudflare 엣지 IP들만 신뢰
    set-real-ip-from: "173.245.48.0/20"
    set-real-ip-from: "103.21.244.0/22"
    set-real-ip-from: "103.22.200.0/22"
    set-real-ip-from: "103.31.4.0/22"
    set-real-ip-from: "141.101.64.0/18"
    set-real-ip-from: "108.162.192.0/18"
    set-real-ip-from: "190.93.240.0/20"
    set-real-ip-from: "188.114.96.0/20"
    set-real-ip-from: "197.234.240.0/22"
    set-real-ip-from: "198.41.128.0/17"
    set-real-ip-from: "2400:cb00::/32"
    set-real-ip-from: "2606:4700::/32"
    set-real-ip-from: "2803:f800::/32"
    set-real-ip-from: "2405:b500::/32"
    set-real-ip-from: "2405:8100::/32"
    set-real-ip-from: "2a06:98c0::/29"
    set-real-ip-from: "2c0f:f248::/32"

    # 디버깅용
    log-format-upstream: >-
      $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent
      "$http_referer" "$http_user_agent" $request_length $request_time
      [$proxy_upstream_name] $upstream_addr $upstream_response_length
      $upstream_response_time $upstream_status $req_id xff=$http_x_forwarded_for

    # Cloudflare를 신뢰할 것이므로 proxy-real-ip-cidr는 생략/미설정

  setAsDefaultIngress: false

  admissionWebhooks:
    patch:
      enabled: true
