apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-petgradle-boot-dp
  namespace: sample-dev
  labels:
    app: sample-petgradle-boot
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-petgradle-boot
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: sample-petgradle-boot
        requires-auth: "true"
    spec:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: sample-petgradle-boot-con
        image: redcedar1/istio-keycloak-demo:0.1   # ✅ 너 이미지로 교체
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault

        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

        env:
        - name: NODE_NAME
          valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
        - name: NODE_IP
          valueFrom: {fieldRef: {fieldPath: status.hostIP}}
        - name: NAMESPACE
          valueFrom: {fieldRef: {fieldPath: metadata.namespace}}
        - name: POD_NAME
          valueFrom: {fieldRef: {fieldPath: metadata.name}}
        - name: POD_IP
          valueFrom: {fieldRef: {fieldPath: status.podIP}}
        - name: JAVA_OPTS_APPEND
          value: |
            -XX:+UseContainerSupport
            -XX:MaxRAMPercentage=70.0
            -XX:InitialRAMPercentage=50.0
            -XX:NewRatio=3
            -XX:MaxMetaspaceSize=512m
            -XX:+UseG1GC
            -XX:+HeapDumpOnOutOfMemoryError
            -XX:HeapDumpPath=/app/logs/$(POD_NAME)_heapdump.hprof
            -Dfile.encoding=UTF-8
            -Djava.security.egd=file:/dev/./urandom
            -Djava.io.tmpdir=/app/tmp
            -Dlogpath=/app/logs
            -Dhostname=$(POD_NAME)

        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]

        livenessProbe:
          httpGet:
            path: /petgradle/actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3

        readinessProbe:
          httpGet:
            path: /petgradle/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3

        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"

        volumeMounts:
        - mountPath: /app/data
          name: data
        - mountPath: /app/logs
          name: log
        - mountPath: /app/tmp
          name: tmp
        - mountPath: /tmp
          name: tmp

      volumes:
      # ✅ PVC 제거 → emptyDir로 대체
      - name: data
        emptyDir: {}
      - name: log
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sample-petgradle-boot-svc
  namespace: sample-dev
  labels:
    app: sample-petgradle-boot
spec:
  type: ClusterIP
  selector:
    app: sample-petgradle-boot
  ports:
  - name: http
    port: 80
    targetPort: 8080